"""
Fake LLM backend for testing and dry runs.

Returns canned responses based on pattern matching in the system prompt.
No API key or network needed — useful for:
  - CI/CD pipelines
  - Development without API costs
  - End-to-end flow testing

Configure via:
  AICOMPANY_LLM_BACKEND=fake
"""
from __future__ import annotations

import json

from aicompany.llm_backend import register_backend

# ── Canned responses ──────────────────────────────────────────────────────────

_EVAL_RESPONSE = json.dumps({
    "clarity": 4, "completeness": 4, "feasibility": 4,
    "risks": ["Fake backend — no real analysis performed"],
    "suggestions": ["Run with a real LLM backend for actual evaluation"],
    "summary": "Fake evaluation — all scores set to 4 (pass threshold).",
    "verdict": "proceed",
})

_CTO_RESPONSE = json.dumps({
    "title": "Fake Project Plan",
    "tech_stack": ["python"],
    "teams_required": ["backend_team"],
    "tasks": [
        {
            "id": "task_001",
            "title": "Implement feature",
            "description": "Implement the requested feature as described in requirements.",
            "assigned_team": "backend_team",
            "depends_on": [],
            "is_checkpoint": False,
        }
    ],
})

_HR_RESPONSE = json.dumps({
    "team": {
        "id": "new_team",
        "name": "New Team",
        "skills": [],
        "members": ["new_lead"],
        "lead_id": "new_lead",
    },
    "persons": [
        {
            "id": "new_lead",
            "name": "Fake Lead",
            "role": "lead",
            "identity": "You are a team lead created by the fake backend.",
            "skills": [],
            "knowledge": [],
            "rules": ["Produce placeholder output."],
            "tools": [],
        }
    ],
    "skills": [],
})

_AUTOFIX_RESPONSE = """\
# Improved Requirements (Auto-generated by Fake Backend)

## Overview
This is a placeholder rewrite. Use a real LLM backend for actual improvements.

## Features
- Feature from original requirements (placeholder)

## Acceptance Criteria
- All features work as described
"""

_DEFAULT_RESPONSE = "This is a placeholder response from the fake LLM backend."


class FakeBackend:
    """LLM backend that returns canned responses without any API calls."""

    def call(self, system: str, user: str, max_tokens: int, model: str) -> str:
        lower = system.lower()
        if "evaluate" in lower and "requirements" in lower:
            return f"```json\n{_EVAL_RESPONSE}\n```"
        if "cto" in lower:
            return f"```json\n{_CTO_RESPONSE}\n```"
        if "hr" in lower or "head of hr" in lower:
            return f"```json\n{_HR_RESPONSE}\n```"
        if "requirements-engineering" in lower or "autofix" in lower:
            return _AUTOFIX_RESPONSE
        # For team execution (brief, execute, synthesize)
        return _DEFAULT_RESPONSE


register_backend("fake", FakeBackend)
